# Default values for demohelmchart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: bhanu2021/demo1
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"


service:
  type: NodePort
  port: 9111
  targetPort: 9111

container:
  name: demohelmchart