apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    {{- include "demohelmchart.labels" . | nindent 4 }}
  name: {{ .Release.Name }}-service
spec:
  ports:
  - name: "http"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "demohelmchart.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type | quote }}